In [3]:
%%time
import sys
import os 
module_path = os.path.abspath(os.path.join('..')) 
if module_path not in sys.path: 
    sys.path.append(module_path)
import tools.Sample_Tools as smpl
import tools.Factor_Cacher as cacher
import tools.Pretreat_Tools as pretreat
from base.JuUnits import excute_for_multidates

import pandas as pd
import numpy as np

%load_ext autoreload
%autoreload 2
%aimport tools.Factor_Cacher


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Wall time: 0 ns


In [40]:
%%time
# factors = cacher.load_caches_adv(['alpha11','alpha24','alpha38','alpha41'],'2021-11-18','2021-11-24')
# codes = factors.index.get_level_values(1).unique()
# dates = factors.index.get_level_values(0).unique()
# data = smpl.get_data(codes.to_list(),dates.min().strftime('%Y-%m-%d'),dates.max().strftime('%Y-%m-%d')).data
# mv_industry = smpl.add_marketvalue_industry(data).drop(columns=data.columns.to_list())
# industy = mv_industry['industry']
# cap = mv_industry['totalCapital']
# adj_weight = np.sqrt(cap)/np.sqrt(cap).sum()
# # adj_weight_mat = pd.DataFrame(np.diag(adj_weight),index=adj_weight.index, columns=adj_weight.index)
# ret_forward = smpl.get_forward_return(data,'close')
# ret_forward.name = 'ret_forward'

# factors = factors.assign(country=1.0, industry = industy)
# factors = pd.get_dummies(factors,'industry')
# del factors['country']
# factors

Wall time: 1.57 s


alpha11  alpha24   alpha38   alpha41  industry_PCB  \
date       code                                                          
2021-11-18 000001  1.081522    -0.45 -0.071362  0.044701             0   
           000002  0.152750    -1.45 -0.137740  0.040979             0   
           000063  0.364765    -0.28 -0.349654  0.029828             0   
           000066  0.318474    -0.73 -0.032221  0.009315             0   
           000069  0.631213    -0.28 -0.057293  0.012834             0   
...                     ...      ...       ...       ...           ...   
2021-11-24 603899  0.716829    -0.00 -0.031443  0.082944             0   
           603939  0.494440    -3.63 -0.257131 -0.053528             0   
           603986  1.171785   -13.87 -0.050580  0.176878             0   
           603993  0.160092    -0.25 -0.611960 -0.023814             0   
           605499  0.524685   -15.55 -0.660235  0.067494             0   

                   industry_中药  industry_乳制品  industry_云基础设施服务  \
date       code                                                  
2021-11-18 000001            0             0                 0   
           000002            0             0                 0   
           000063            0             0                 0   
           000066            0             0                 0   
           000069            0             0                 0   
...                        ...           ...               ...   
2021-11-24 603899            0             0                 0   
           603939            0             0                 0   
           603986            0             0                 0   
           603993            0             0                 0   
           605499            0             0                 0   

                   industry_云软件服务  industry_产业地产  ...  industry_铁路运输  \
date       code                                   ...                  
2021-11-18 000001               0              0  ...              0   
           000002               0              0  ...              0   
           000063               0              0  ...              0   
           000066               0              0  ...              0   
           000069               0              0  ...              0   
...                           ...            ...  ...            ...   
2021-11-24 603899               0              0  ...              0   
           603939               0              0  ...              0   
           603986               0              0  ...              0   
           603993               0              0  ...              0   
           605499               0              0  ...              0   

                   industry_铜  industry_铝  industry_锂  industry_防水材料  \
date       code                                                        
2021-11-18 000001           0           0           0              0   
           000002           0           0           0              0   
           000063           0           0           0              0   
           000066           0           0           0              0   
           000069           0           0           0              0   
...                       ...         ...         ...            ...   
2021-11-24 603899           0           0           0              0   
           603939           0           0           0              0   
           603986           0           0           0              0   
           603993           0           0           0              0   
           605499           0           0           0              0   

                   industry_集成电路设计  industry_面板  industry_风力发电  industry_风电整机  \
date       code                                                                 
2021-11-18 000001                0            0              0              0   
           000002                0            0              0              0   


In [103]:
k=factors.shape[1]
diag_r = np.diag(np.ones(k))
location = k-1
r=np.delete(diag_r,location,axis=1)

r


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [9]:
adj_weight

date        code  
2021-11-24  000001    0.006190
            000002    0.004977
            000063    0.004130
            000066    0.002145
            000069    0.002378
                        ...   
            603899    0.002456
            603939    0.001951
            603986    0.003391
            603993    0.003765
            605499    0.002920
Name: totalCapital, Length: 255, dtype: float64

In [57]:
# import Analysis_Funs as af
dat='2021-11-18'
f = af.get_LR_params_fast(factors.loc[dat,:].values,ret_forward[dat].values)
f
# factors.shape


array([-6.46650584e-03, -1.75750531e-04,  2.26191833e-01, -1.51680769e-02,
       -2.77526332e-02,  4.90412624e-02,  2.80169458e-02,  3.99594053e-02,
        6.22880280e-02,  8.39990202e-02,  2.13886050e-02,  1.19790836e-01,
        6.36815021e-02,  4.55100654e-01,  1.00350810e-01,  1.17391245e-01,
        1.14322960e-01,  2.12301140e-01,  1.64441379e-02,  8.78179646e-02,
        9.32841778e-02,  3.02392768e-02,  1.05842160e-01, -2.65043394e-01,
        3.05797947e-02,  8.75976409e-02,  1.96671778e-01,  2.27805119e-02,
        2.39188849e-02, -5.56836596e-03,  3.59830702e-03,  1.17040205e-01,
       -2.57177335e-01,  1.10796742e-01,  4.69772759e-02,  1.96436340e-02,
        2.11120839e-01,  5.13046357e-02, -1.68914983e-01,  9.63181777e-02,
        5.84696095e-02,  3.72536812e-02,  2.67597330e-02,  3.45860265e-01,
        4.57719039e-02,  7.02498816e-02,  6.62648132e-02,  4.33388916e-02,
        3.19517852e-01,  1.04566079e-01,  3.88351415e-01,  4.64080943e-02,
        3.23087525e-02,  

In [58]:
ret_forward[dat].values

array([ 1.96629213e-02,  4.24305919e-02,  5.34255185e-03,  1.69992609e-02,
        2.41935484e-02,  9.52380952e-03,  1.45348837e-03,  1.76817289e-02,
        3.44827586e-02, -3.13301054e-03,  4.68140442e-02,  3.32778702e-03,
        2.22222222e-04,  3.30719247e-02, -3.83171124e-05,  8.30564784e-03,
        4.47552448e-03, -1.67901406e-02, -1.91021968e-03, -1.03189493e-02,
        8.17995910e-03, -1.34770889e-03,  6.23229462e-02,  1.38696255e-02,
        3.01027900e-02,  9.61538462e-03,  1.90777490e-02, -1.34788190e-02,
        3.98936170e-03, -8.45899228e-03,  3.80331432e-03,  1.07019201e-02,
        6.37707948e-02,  9.99666778e-03,  1.37551582e-03,  5.45627829e-02,
        2.46305419e-03,  5.54785021e-03,  2.25080386e-03,  1.43415906e-02,
       -1.00559719e-02,  1.07573150e-02,  1.42314991e-02,  1.00105374e-01,
        1.42014420e-02,  1.67890871e-02, -2.46575342e-02, -2.30109204e-02,
        1.17083555e-02,  6.37055388e-03,  4.80065094e-02,  5.77154309e-02,
        3.05810398e-03,  